'use client';
import {useEffect,useState} from 'react';
import {BarChart3,Inbox,Search,Send,Clock,RefreshCw,Languages,MessageSquare} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {messageLanguage} from '@/lib/message-labels';
type Count={language:string;count:number};
type Data={today:string;firstSearch:string|null;summary:{searches:number;found:number;messages:number;pending:number;sent:number};languages:{search:Count[];messages:Count[]};questions:{search:{question:string;language:string;count:number}[];messages:{question:string;language:string;count:number}[]};activity:{search:{day:string;count:number}[];messages:{day:string;count:number}[];sent:{day:string;count:number}[]}};
const number=(value:number)=>value.toLocaleString('ar-SA');
const shortDate=(value:string)=>new Intl.DateTimeFormat('ar-SA',{month:'short',day:'numeric',calendar:'gregory',timeZone:'Asia/Riyadh'}).format(new Date(value+'T12:00:00+03:00'));
export function AdminAnalytics({onExpired}:{onExpired:()=>void}){
 const [days,setDays]=useState('30'),[mode,setMode]=useState<'search'|'messages'>('search'),[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');fetch('/api/admin/analytics?days='+days,{cache:'no-store',signal:abort.signal}).then(async r=>{if(r.status===401){onExpired();return;}const result=await r.json() as Data&{error?:string};if(!r.ok)throw Error(result.error||'تعذر تحميل الإحصاءات.');setData(result);}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'تعذر تحميل الإحصاءات.');}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[days,revision,onExpired]);
 const languages=data?.languages[mode]??[],questions=data?.questions[mode]??[],total=languages.reduce((sum,row)=>sum+row.count,0),max=Math.max(1,...languages.map(row=>row.count)),questionMax=Math.max(1,...questions.map(row=>row.count));
 const dayCount=days==='7'?7:days==='30'?30:90;
 const activity=Array.from({length:dayCount},(_,i)=>{const day=new Date(Date.parse((data?.today??new Date().toISOString().slice(0,10))+'T12:00:00Z')-(dayCount-1-i)*86400000).toISOString().slice(0,10);return {day,search:data?.activity.search.find(r=>r.day===day)?.count??0,messages:data?.activity.messages.find(r=>r.day===day)?.count??0,sent:data?.activity.sent.find(r=>r.day===day)?.count??0};});
 const maxActivity=Math.max(1,...activity.flatMap(row=>[row[mode],row.sent]));
 return <section className="admin-analytics" aria-label="التحليلات" aria-busy={loading}>
  <div className="analytics-toolbar"><div><h2><BarChart3 size={22}/>التحليلات</h2><p>قراءة تفاعل المستفيدين ومتابعة الردود</p></div><div className="analytics-period"><select aria-label="الفترة الزمنية" value={days} onChange={e=>setDays(e.target.value)}><option value="7">آخر ٧ أيام</option><option value="30">آخر ٣٠ يومًا</option><option value="90">آخر ٩٠ يومًا</option><option value="all">كل الفترات</option></select><Button variant="outline" size="icon" aria-label="تحديث التحليلات" disabled={loading} onClick={()=>setRevision(v=>v+1)}><RefreshCw size={17} className={loading?'animate-spin':''}/></Button></div></div>
  {error&&<p role="alert" className="error-message">{error}</p>}
  {!data?<p role="status" className="admin-empty">{loading?'جارٍ تحميل الإحصاءات…':'لا تتوفر إحصاءات الآن.'}</p>:<>
   <div className="analytics-summary">{[{label:'عمليات البحث',value:data.summary.searches,icon:Search},{label:'الرسائل الواردة',value:data.summary.messages,icon:Inbox},{label:'الردود المرسلة',value:data.summary.sent,icon:Send},{label:'بانتظار الإكمال',value:data.summary.pending,icon:Clock}].map(card=><div key={card.label}><card.icon size={20}/><span>{card.label}</span><strong>{number(card.value)}</strong></div>)}</div>
   <div className="analytics-mode" aria-label="نوع الإحصاءات"><Button variant={mode==='search'?'default':'outline'} aria-pressed={mode==='search'} onClick={()=>setMode('search')}>أسئلة البحث</Button><Button variant={mode==='messages'?'default':'outline'} aria-pressed={mode==='messages'} onClick={()=>setMode('messages')}>رسائل الإدارة</Button></div>
   <div className="analytics-grid"><section className="analytics-card"><h3><Languages size={19}/>اللغات الأكثر مشاركة</h3>{languages.length?<ol className="analytics-bars">{languages.map(row=><li key={row.language}><div><span>{messageLanguage(row.language)}</span><b>{number(row.count)} <small>· {number(Math.round(row.count/total*100))}٪</small></b></div><div className="analytics-track" aria-hidden="true"><span style={{width:row.count/max*100+'%'}}/></div></li>)}</ol>:<p className="analytics-empty">لا توجد مشاركات في هذه الفترة.</p>}</section>
   <section className="analytics-card"><h3><MessageSquare size={19}/>الأسئلة والعبارات الأكثر تكرارًا</h3>{questions.length?<ol className="analytics-bars analytics-question-bars">{questions.map((row,i)=><li key={row.language+row.question}><div><span dir="auto" title={row.question}>{row.question}</span><b>{number(row.count)}</b></div><small>{messageLanguage(row.language)}</small><div className="analytics-track" aria-hidden="true"><span style={{width:row.count/questionMax*100+'%'}}/></div></li>)}</ol>:<p className="analytics-empty">تظهر العبارات المتكررة مع وصول المشاركات.</p>}</section></div>
   <section className="analytics-card analytics-activity"><div className="analytics-chart-heading"><h3>النشاط اليومي</h3><div className="analytics-legend"><span><i/>{mode==='search'?'البحث':'الوارد'}</span><span><i/>الصادر</span></div></div><div className="analytics-daily-chart" role="img" aria-label={'النشاط اليومي خلال آخر '+dayCount+' يومًا؛ تظهر الأعداد عند تحديد اليوم.'} dir="ltr">{activity.map(row=><div key={row.day} className="analytics-day" tabIndex={0} aria-label={shortDate(row.day)+': '+(mode==='search'?'البحث':'الوارد')+' '+row[mode]+', الصادر '+row.sent}><div className="analytics-day-bars"><span style={{height:row[mode]/maxActivity*100+'%'}}/><span style={{height:row.sent/maxActivity*100+'%'}}/></div><span className="analytics-day-tooltip">{shortDate(row.day)}<br/>{mode==='search'?'البحث':'الوارد'}: {number(row[mode])}<br/>الصادر: {number(row.sent)}</span></div>)}</div><div className="analytics-axis" dir="ltr"><span>{shortDate(activity[0].day)}</span><span>{shortDate(activity.at(-1)!.day)}</span></div></section>
   <p className="analytics-note">{mode==='search'?(data.firstSearch?'بدأ تسجيل عمليات البحث في '+new Intl.DateTimeFormat('ar-SA',{dateStyle:'medium',calendar:'gregory',timeZone:'Asia/Riyadh'}).format(new Date(data.firstSearch))+'.':'تبدأ إحصاءات البحث مع أول عملية بحث بعد تفعيلها.'):'تُحتسب الرسائل المحفوظة، دون تكرار رسائل التواصل التي تم الرد عليها.'} {mode==='search'&&'الأعداد تمثل المشاركات وليست عدد الأشخاص.'} {days==='all'&&'الرسم اليومي يعرض آخر ٩٠ يومًا.'}</p>
  </>}
 </section>;
}
