'use client';
import {sourceReferenceLink} from '@/lib/source-links';
import {useCallback,useEffect,useState} from 'react';
import {Check,Download,FolderOpen,LoaderCircle,Printer,RefreshCw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Input} from '@/components/ui/input';
import {Badge} from '@/components/ui/badge';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {decisions} from '@/lib/export-case';
import type {CaseRecord,ReviewDecision,ReviewEvent} from '@/lib/types';
type Summary=Omit<CaseRecord,'response'>;
async function payload<T>(response:Response):Promise<T>{const d=await response.json() as T&{error?:string};if(!response.ok)throw Error(d.error||'تعذرت العملية.');return d;}
const date=(value:string)=>new Intl.DateTimeFormat('ar-SA',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Riyadh',calendar:'gregory'}).format(new Date(value));
export function CaseWorkspace({initialCase}:{initialCase:CaseRecord|null}){
 const [list,setList]=useState<Summary[]>([]),[selected,setSelected]=useState<CaseRecord|null>(initialCase),[events,setEvents]=useState<ReviewEvent[]>([]),[filter,setFilter]=useState(''),[decision,setDecision]=useState<ReviewDecision>(initialCase?.decision||'pending'),[note,setNote]=useState(initialCase?.note||''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const refresh=useCallback(async()=>{const d=await payload<{cases:Summary[]}>(await fetch('/api/cases'));setList(d.cases);},[]);
 const open=useCallback(async(id:string)=>{setBusy(true);setError('');setNotice('');try{const d=await payload<{case:CaseRecord;events:ReviewEvent[]}>(await fetch(`/api/cases/${encodeURIComponent(id)}`));setSelected(d.case);setDecision(d.case.decision);setNote(d.case.note);setEvents(d.events);}catch(e){setError(e instanceof Error?e.message:'تعذر فتح الحالة.');}finally{setBusy(false);}},[]);
 useEffect(()=>{void refresh().catch(e=>setError(e instanceof Error?e.message:'تعذر تحميل الملفات.'));if(initialCase)void open(initialCase.id);},[refresh,open,initialCase]);
 async function review(){if(!selected||busy)return;setBusy(true);setError('');setNotice('');try{const d=await payload<{case:CaseRecord;events:ReviewEvent[]}>(await fetch(`/api/cases/${selected.id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision,note,revision:selected.revision})}));setSelected(d.case);setEvents(d.events);setNotice('حُفظ القرار مع تاريخه وسببه.');await refresh();}catch(e){setError(e instanceof Error?e.message:'تعذر تسجيل القرار.');}finally{setBusy(false);}}
 const visible=list.filter(c=>`${c.question} ${c.topic} ${decisions[c.decision]}`.includes(filter));
 return <main className="case-workspace"><div className="section-heading"><div><span className="eyebrow"><FolderOpen size={17}/> ملفاتك المحفوظة</span><h1>من الدليل إلى قرار المراجع.</h1><p>يُحفظ السؤال والأدلة في مسودة مستقلة. اعتمد النتيجة بعد قراءة المصدر، أو أحلها إلى مختص.</p></div><Button variant="outline" onClick={()=>void refresh().catch(e=>setError(e.message))} disabled={busy}><RefreshCw size={16}/> تحديث</Button></div>{error&&<p role="alert" className="error-message">{error}</p>}{notice&&<p role="status" className="success-message"><Check size={16}/>{notice}</p>}
 <div className="case-columns"><aside className="case-list"><label htmlFor="case-filter">ابحث في آخر ٥٠ حالة</label><Input id="case-filter" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="السؤال أو الموضوع أو القرار"/>{!visible.length?<p className="muted-text">{filter?'لا توجد حالة تطابق البحث.':'لم تحفظ حالة بعد. ابدأ بسؤال ثم اختر حفظ ملف الحالة.'}</p>:visible.map(c=><button type="button" key={c.id} className={`case-list-item ${selected?.id===c.id?'active':''}`} onClick={()=>void open(c.id)} disabled={busy}><strong>{c.question}</strong><span>{c.topic} · <bdi>{c.level}</bdi></span><small>{decisions[c.decision]} · {date(c.createdAt)}</small></button>)}</aside>
 <section className="case-detail" aria-live="polite" aria-busy={busy}>{selected?<><div className="case-head"><Badge variant="outline">{decisions[selected.decision]}</Badge><span>إصدار <bdi>{selected.revision}</bdi> · {date(selected.updatedAt)}</span></div><h2>{selected.question}</h2><div className="case-analysis"><span>{selected.topic}</span><span>مستوى <bdi>{selected.level}</bdi></span><span>{selected.response.analysis.method==='model'?'تحليل النموذج':'اقتراح أولي بقواعد محدودة'}</span></div><p>{selected.response.message}</p>{selected.response.answer.length>0&&<div className="answer-box"><h3>مسودة شرح مولدة — تحتاج مراجعة</h3>{selected.response.answer.map((a,i)=><p key={i}>{a.text}<small>معرفات الأدلة: <bdi>{a.evidenceIds.join('، ')}</bdi></small></p>)}</div>}
 <h3>الأدلة المحفوظة وقت إنشاء الحالة</h3>{!selected.response.evidence.length&&<p className="muted-text">لا يوجد دليل كافٍ في هذه الحالة. لا يمكن اعتمادها بهذه الصورة.</p>}{selected.response.evidence.map((e,i)=><article className="saved-evidence" key={`${e.source.id}-${i}`}><strong>{e.source.title}</strong><blockquote>{e.excerpt}</blockquote><p>{e.source.grade} · {e.source.attribution}</p><a href={sourceReferenceLink(e.source).url||undefined} target="_blank" rel="noopener noreferrer">افتح المصدر الأصلي <bdi>{e.source.id}</bdi></a><small>الجلب: {date(e.source.retrievedAt)} · {e.source.accessMode==='live'?'مباشر':'نسخة محفوظة'}</small></article>)}
 <div className="review-form"><h3>قرار المراجع</h3><p className="muted-text">هذا القرار يُسجَّل باسم مستخدم التطبيق، ويحتاج مراجعة علمية مؤهلة قبل استخدامه خارج التجربة.</p><label htmlFor="review-decision">القرار</label><Select value={decision} onValueChange={v=>setDecision(v as ReviewDecision)} disabled={busy}><SelectTrigger id="review-decision" className="decision-select"><SelectValue/></SelectTrigger><SelectContent dir="rtl">{Object.entries(decisions).map(([v,label])=><SelectItem key={v} value={v}>{label}</SelectItem>)}</SelectContent></Select><label htmlFor="review-note">سبب القرار</label><Textarea id="review-note" value={note} onChange={e=>setNote(e.target.value)} rows={3} maxLength={2000} placeholder="ما الدليل الذي قرأته؟ ولماذا اخترت هذا القرار؟" disabled={busy}/><Button onClick={()=>void review()} disabled={busy|| (decision!=='pending'&&note.trim().length<10)}>{busy?<LoaderCircle className="animate-spin"/>:<Check size={16}/>} سجّل القرار</Button></div>
 <div className="case-export no-print"><Button variant="outline" asChild><a href={`/api/cases/${selected.id}/export`}><Download size={16}/> تنزيل ملف الحالة</a></Button><Button variant="outline" asChild><a href={`/api/cases/${selected.id}/export?format=json`}><Download size={16}/> <bdi dir="ltr">JSON</bdi></a></Button><Button variant="outline" onClick={()=>window.print()}><Printer size={16}/> طباعة أو حفظ <bdi dir="ltr">PDF</bdi></Button></div>
 <div className="review-history"><h3>سجل القرارات</h3>{events.map(e=><div key={e.id}><strong>{decisions[e.toDecision]}</strong><span>{date(e.createdAt)} · <bdi dir="auto">{e.actor}</bdi></span><p>{e.note}</p></div>)}</div><p className="case-provenance">معرف الحالة: <bdi dir="ltr">{selected.id}</bdi><br/>الإنشاء: {date(selected.createdAt)}. تغيير السؤال يُنشئ حالة جديدة ولا ينقل اعتماد هذه الحالة.</p></>:<div className="empty-result"><FolderOpen size={30}/><h2>اختر ملفًا لفتحه</h2><p>ستجد هنا السؤال والأدلة وسبب القرار وسجله.</p></div>}</section></div></main>;
}
