'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import type {Referral} from '@/lib/referrals';
export function CommitteeInbox(){
 const [items,setItems]=useState<Referral[]>([]),[error,setError]=useState(''),[enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Referral|null>(null),[answer,setAnswer]=useState(''),[sources,setSources]=useState(''),[confirmed,setConfirmed]=useState(false);
 async function load(){const r=await fetch('/api/committee');const d=await r.json() as {error:string;items:Referral[];emailDeliveryEnabled:boolean};if(!r.ok)throw Error(d.error);setItems(d.items);setEnabled(d.emailDeliveryEnabled);}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 async function approve(){if(!selected||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/committee',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,answer,sources:sources.split('\n').map(s=>s.trim()).filter(Boolean),confirmed})});const d=await r.json() as {error:string};if(!r.ok)throw Error(d.error);setSelected(null);await load();}catch(e){setError(e instanceof Error?e.message:'تعذر الحفظ');}finally{setBusy(false);}}
 const status:Record<string,string>={pending:'بانتظار المراجعة',approved:'معتمد — لم يرسل',sending:'جارٍ الإرسال',sent:'قبله مزود البريد',delivery_unknown:'يلزم فحص سجل البريد قبل إعادة الإرسال'};
 return <main className="committee-panel" dir="rtl"><h1>الأسئلة المحالة للمراجعة</h1>{!enabled&&<p>البريد غير مفعّل. يمكن حفظ الاعتماد؛ لن تُرسل رسائل قبل تفعيل الخدمة.</p>}{error&&<p role="alert">{error}</p>}<Button variant="outline" onClick={()=>void load().catch(e=>setError(e.message))}>تحديث</Button>{items.map(item=><article key={item.id} className="evidence-card"><p dir="auto">{item.question}</p><p><bdi>{item.language}</bdi> · {status[item.status]??item.status}</p><Button variant="outline" onClick={()=>{setSelected(item);setAnswer(item.answer);setSources((JSON.parse(item.sources) as string[]).join('\n'));setConfirmed(false);}}>فتح السؤال</Button></article>)}{selected&&<section className="referral-form"><h2 dir="auto">{selected.question}</h2><p>لغة الرد: <bdi>{selected.language}</bdi> · <bdi>{selected.email}</bdi></p><label htmlFor="committee-answer">الرد المعتمد بنفس لغة السائل</label><Textarea id="committee-answer" dir="auto" value={answer} onChange={e=>setAnswer(e.target.value)} disabled={selected.status!=='pending'} maxLength={12000}/><label htmlFor="committee-sources">روابط المراجع المتصلة — رابط في كل سطر</label><Textarea id="committee-sources" dir="ltr" value={sources} onChange={e=>setSources(e.target.value)} disabled={selected.status!=='pending'}/><label className="referral-consent"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/><span>راجعت الرد شرعيًا ولغويًا وتحققت من مطابقته للمراجع.</span></label><Button disabled={busy||!confirmed||!['pending','approved'].includes(selected.status)} onClick={()=>void approve()}>{enabled?'اعتماد وإرسال الرد':'حفظ الاعتماد'}</Button><Button variant="ghost" onClick={()=>setSelected(null)}>إغلاق</Button></section>}</main>;
}
