'use client';
import stats from '@/lib/library-statistics.json';
import {useState} from 'react';
import {BookOpen,Search} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {currentReferences,upcomingReferences,libraryLanguageCounts,type Bilingual,type ReferenceEntry} from '@/lib/reference-directory';
function Text({value,className=''}:{value:Bilingual;className?:string}){return <div className={'bilingual-copy '+className}><p lang="ar" dir="rtl">{value.ar}</p><p lang="en" dir="ltr">{value.en}</p></div>;}
function References({rows,search}:{rows:ReferenceEntry[];search:string}){
 const filtered=rows.map((row,index)=>({...row,number:index+1})).filter(row=>[row.name.ar,row.name.en,row.material.ar,row.material.en,row.languages.ar,row.languages.en].join(' ').toLowerCase().includes(search.toLowerCase().trim()));
 return <div className="reference-directory-list"><table className="reference-directory-table"><thead><tr><th aria-label="Number">#</th><th>المرجع والمواد<span lang="en" dir="ltr">Reference & materials</span></th><th>حجم المحتوى<span lang="en" dir="ltr">Collection size</span></th><th>اللغات<span lang="en" dir="ltr">Languages</span></th></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td className="reference-index"><bdi>{String(row.number).padStart(2,'0')}</bdi></td><td className="reference-description"><a href={row.url} target="_top" rel="external"><Text value={row.name} className="reference-name"/></a><Text value={row.material}/></td><td className="reference-size"><Text value={row.quantity}/></td><td className="reference-languages"><Text value={row.languages}/></td></tr>)}</tbody></table>{!filtered.length&&<Text className="reference-empty" value={{ar:'لا توجد مراجع مطابقة.',en:'No matching references.'}}/>}</div>;
}
export function ResourceCatalog(){
 const [search,setSearch]=useState('');
 return <main className="reference-directory" dir="rtl" lang="ar">
  <header className="reference-directory-heading"><div><h1>مراجع مدار البيان</h1><p lang="en" dir="ltr">Madar Al Bayan References</p></div><BookOpen size={30}/></header>
  <div className="reference-totals"><div><strong><bdi>{stats.totalHadithTexts.toLocaleString('en-US')}</bdi></strong><Text value={{ar:'نص حديث مع الترجمات',en:'Hadith texts including translations'}}/><small>٣٬٥٨٢ حديثًا · <bdi>3,582 hadith</bdi></small></div><div><strong><bdi>{stats.totalQuranVerses.toLocaleString('en-US')}</bdi></strong><Text value={{ar:'نص آية وترجمة معانيها',en:'Verse texts and translations of meanings'}}/><small>٦٬٢٣٦ آية · <bdi>6,236 verses</bdi></small></div><div><strong><bdi>{Object.keys(stats.languages).length}</bdi></strong><Text value={{ar:'لغات للمكتبة الحالية',en:'Languages in the current library'}}/></div></div>
  <details className="reference-language-details"><summary>توزيع نصوص الحديث حسب اللغة <span lang="en" dir="ltr">Hadith texts by language</span></summary><div className="reference-language-grid">{libraryLanguageCounts.map(row=><div key={row.en}><Text value={{ar:row.ar,en:row.en}}/><strong><bdi>{row.texts.toLocaleString('en-US')}</bdi></strong><span>الشروح: <bdi>{row.explanations.toLocaleString('en-US')}</bdi><span lang="en" dir="ltr">Explanations</span></span></div>)}</div></details>
  <div className="reference-search"><Search size={18}/><Input aria-label="Search references / البحث في المراجع" placeholder="اسم المرجع أو الموضوع · Search references" value={search} onChange={e=>setSearch(e.target.value)}/></div>
  <section aria-labelledby="current-references"><div className="reference-section-heading"><h2 id="current-references">المراجع الحالية<span lang="en" dir="ltr">Current references</span></h2><bdi>{String(currentReferences.length).padStart(2,'0')}</bdi></div><References rows={currentReferences} search={search}/></section>
  <section aria-labelledby="upcoming-references"><div className="reference-section-heading"><h2 id="upcoming-references">مراجع قيد الإعداد للإضافة<span lang="en" dir="ltr">Upcoming references</span></h2><bdi>{String(upcomingReferences.length).padStart(2,'0')}</bdi></div><References rows={upcomingReferences} search={search}/></section>
  <Text className="reference-count-note" value={{ar:'تشمل أعداد النصوص الإصدارات العربية والترجمات المنشورة المتحقق منها بتاريخ ٥ أكتوبر ٢٠٢٦. تضم المكتبة كذلك ٦٤٤ إجابة منشورة و٥٨ بطاقة مصطلح. إحصاءات الناشر وأعداد لغاته الإضافية موضحة في كل صف؛ ولا تعني حفظ كامل فهرسه أو توفر كل مادة بكل لغة.',en:'Text totals include Arabic editions and published translations verified on 5 October 2026. The collection also includes 644 published answers and 58 term cards. Publisher-wide totals and additional languages are identified in each row; they do not imply that the full catalog is saved here or that every item exists in every language.'}}/>
 </main>;
}
