'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
type Report={checkedAt:string;contextConfigured:boolean;integratedSources:{id:number;publisher:string;mode:string;capability:string;live:{ok:boolean;status:string;reason?:string;httpStatus?:number;records?:number;fields?:string[]};saved:{language:string;ok:boolean}[]}[];catalog:{id:number;name:string;integration:string}[]};
const labels:Record<string,string>={connected:'نجح استرجاع العينة','catalog-connected':'نجح استرجاع الفهرس؛ دون نص كامل',unavailable:'تعذر استرجاع المحتوى','needs-key':'بانتظار مفتاح الجهة','metadata-only':'لم يُتحقق من نص فعلي'};
export function SourceHealth({expanded=false}:{expanded?:boolean}){
 const [report,setReport]=useState<Report|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function check(){setBusy(true);setError('');try{const r=await fetch('/api/status',{cache:'no-store'});if(!r.ok)throw Error();setReport(await r.json() as Report);}catch{setError('تعذر إكمال الفحص. حاول مجددًا.');}finally{setBusy(false);}}
 return <details className="source-health" open={expanded||undefined}><summary>حالة ربط المصادر</summary><Button variant="outline" disabled={busy} onClick={()=>void check()}>{busy?'جارٍ فحص محتوى الجهات…':'فحص الربط الآن'}</Button>{error&&<p role="alert">{error}</p>}{report&&<><p>فهم السياق: {report.contextConfigured?'مفتاح الخدمة مضبوط؛ النتيجة تعتمد على استجابة المزود.':'غير مفعّل — لا تُعرض المطابقات العامة قبل التحقق من السياق.'}</p><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>المصدر</th><th>نتيجة الطلب</th><th>المحتوى المرتبط</th><th>النسخ المحفوظة</th></tr></thead><tbody>{report.integratedSources.map(source=><tr key={source.id}><td><bdi>{source.publisher}</bdi></td><td>{labels[source.live.status]??source.live.status}{source.live.httpStatus&&<bdi> ({source.live.httpStatus})</bdi>}{source.live.reason&&<small><bdi>{source.live.reason}</bdi></small>}{source.live.fields&&<small dir="ltr">{source.live.fields.join(', ')}</small>}</td><td>{source.capability}</td><td>{source.saved.length?`${source.saved.filter(x=>x.ok).length} / ${source.saved.length} لغات`:'—'}</td></tr>)}</tbody></table></div><p>فحص عيّنات بتاريخ <bdi>{new Date(report.checkedAt).toLocaleString('ar-SA')}</bdi>. نجاح العينة لا يعني استيراد جميع محتويات الجهة.</p><p>خوادم MCP بوابات إلى المحتوى، ولا تُحتسب مراجع مستقلة. فحص الصوت يتحقق من الفهرس والرابط، وليس جميع التسجيلات.</p></>}</details>;
}
