import extraLanguages from '@/lib/added-language-copy.json';
// Only expose languages with audited full-text banks and saved source recovery.
// The publisher's larger title-only catalog is not a promise of answer coverage.
export const languages = [
  {code:'en',name:'English'}, {code:'ar',name:'العربية'},
  {code:'fr',name:'Français'}, {code:'es',name:'Español'},
  {code:'zh',name:'中文'}, {code:'hi',name:'हिन्दी'},
  {code:'fa',name:'فارسی'}, {code:'id',name:'Bahasa Indonesia'}, {code:'ur',name:'اردو'},
] as const;
export type Language = string;
export function isRTL(language:string){return ['ar','fa','ur','ps','ug','prs','ku'].includes(language);}
export function isLanguage(value:unknown):value is Language {return languages.some(l=>l.code===value);}
type Copy = {
  brand:string; ask:string; placeholder:string; search:string; searching:string; close:string;
  menu:string; source:string; original:string; hadith:string; explanation:string; references:string;
  openSource:string; copy:string; copied:string; error:string; invalid:string; busy:string;
  insufficient:string; unavailable:string; draft:string; draftNote:string;
  live:string; snapshot:string; mixed:string; retrieved:string; back:string;
  cases:string; catalog:string; save:string; saving:string; examples:readonly string[];
};
const localizedCopy:Record<string,Copy> = {
  en:{brand:'Madar Al Bayan',ask:'Ask Madar Al Bayan',placeholder:'Write your question…',search:'Search',searching:'Searching…',close:'Close',menu:'Menu',source:'Source',original:'Published source text',hadith:'Hadith',explanation:'Published explanation',references:'References in the Arabic original',openSource:'Open source',copy:'Copy',copied:'Copied',error:'Something went wrong. Please try again.',invalid:'Please write a question of 1–1,000 characters.',busy:'Please wait for the current search.',insufficient:"No matching source text was found. Try a shorter question or different keywords.",unavailable:'The source translation is temporarily unavailable. Please try again.',draft:'AI-generated draft',draftNote:'Separate from the source text; requires review.',live:'From the source',snapshot:'Saved source text',mixed:'Live and saved sources',retrieved:'Retrieved',back:'Back to search',cases:'Review files (Arabic)',catalog:'Reference catalog (Arabic)',save:'Save for review',saving:'Saving…',examples:['What is ihsan?','What is intention in Islam?']},
  ar:{brand:'مدار البيان',ask:'اسأل مدار البيان',placeholder:'اكتب سؤالك هنا…',search:'ابحث',searching:'جارٍ البحث…',close:'إغلاق',menu:'القائمة',source:'المصدر',original:'النص المنشور في المصدر',hadith:'الحديث',explanation:'الشرح المنشور',references:'المراجع في الأصل العربي',openSource:'افتح المصدر',copy:'نسخ النتيجة',copied:'تم النسخ',error:'تعذر إكمال الطلب. حاول مجددًا.',invalid:'اكتب سؤالًا بين ١ و١٠٠٠ حرف.',busy:'انتظر اكتمال البحث الحالي.',insufficient:"لم أجد نصًا مناسبًا. جرّب سؤالًا أقصر أو كلمات أخرى.",unavailable:'تعذر الوصول إلى ترجمة المصدر الآن. حاول مجددًا.',draft:'مسودة شرح مولدة',draftNote:'منفصلة عن النص الأصلي وتحتاج مراجعة.',live:'من المصدر مباشرة',snapshot:'نصوص محفوظة من المصدر',mixed:'نصوص مباشرة ومحفوظة',retrieved:'تاريخ الجلب',back:'العودة للسؤال',cases:'ملفات الحالات',catalog:'المراجع',save:'حفظ النتيجة للمراجعة',saving:'جارٍ الحفظ…',examples:['ما معنى الإحسان؟','ما معنى النية؟']},
  fr:{brand:'Madar Al Bayan',ask:'Posez votre question',placeholder:'Écrivez votre question…',search:'Rechercher',searching:'Recherche…',close:'Fermer',menu:'Menu',source:'Source',original:'Texte publié par la source',hadith:'Hadith',explanation:'Explication publiée',references:'Références du texte arabe original',openSource:'Ouvrir la source',copy:'Copier',copied:'Copié',error:'Une erreur est survenue. Réessayez.',invalid:'Écrivez une question de 1 à 1 000 caractères.',busy:'Veuillez attendre la fin de la recherche.',insufficient:"Aucun texte pertinent trouvé. Essayez une question plus courte ou d’autres mots-clés.",unavailable:'La traduction de la source est temporairement indisponible. Réessayez.',draft:'Brouillon généré par IA',draftNote:'Distinct du texte source ; nécessite une vérification.',live:'Depuis la source',snapshot:'Texte source enregistré',mixed:'Sources directes et enregistrées',retrieved:'Consulté le',back:'Retour à la recherche',cases:'Dossiers de révision (arabe)',catalog:'Références (arabe)',save:'Enregistrer pour révision',saving:'Enregistrement…',examples:['Qu’est-ce que l’ihsan ?','Que signifie l’intention en islam ?']},
  es:{brand:'Madar Al Bayan',ask:'Haz tu pregunta',placeholder:'Escribe tu pregunta…',search:'Buscar',searching:'Buscando…',close:'Cerrar',menu:'Menú',source:'Fuente',original:'Texto publicado por la fuente',hadith:'Hadiz',explanation:'Explicación publicada',references:'Referencias del original árabe',openSource:'Abrir fuente',copy:'Copiar',copied:'Copiado',error:'Se produjo un error. Inténtalo de nuevo.',invalid:'Escribe una pregunta de entre 1 y 1000 caracteres.',busy:'Espera a que termine la búsqueda.',insufficient:"No se encontró un texto pertinente. Prueba una pregunta más breve u otras palabras clave.",unavailable:'La traducción de la fuente no está disponible temporalmente. Inténtalo de nuevo.',draft:'Borrador generado por IA',draftNote:'Separado del texto original; requiere revisión.',live:'Desde la fuente',snapshot:'Texto de la fuente guardado',mixed:'Fuentes directas y guardadas',retrieved:'Consultado el',back:'Volver a buscar',cases:'Archivos de revisión (árabe)',catalog:'Referencias (árabe)',save:'Guardar para revisión',saving:'Guardando…',examples:['¿Qué es el ihsan?','¿Qué significa la intención en el islam?']},
  zh:{brand:'Madar Al Bayan',ask:'提出您的问题',placeholder:'请输入您的问题…',search:'搜索',searching:'搜索中…',close:'关闭',menu:'菜单',source:'来源',original:'来源中发表的文本',hadith:'圣训',explanation:'已发表的解说',references:'阿拉伯语原文的参考资料',openSource:'查看来源',copy:'复制',copied:'已复制',error:'出现错误，请重试。',invalid:'请输入1至1000个字符的问题。',busy:'请等待当前搜索完成。',insufficient:"未找到相关原文。请尝试更简短的问题或其他关键词。",unavailable:'来源译文暂时无法获取，请重试。',draft:'人工智能生成的草稿',draftNote:'与来源原文分开显示，需经审核。',live:'直接来自来源',snapshot:'已保存的来源文本',mixed:'在线及已保存的来源',retrieved:'获取日期',back:'返回搜索',cases:'审核记录（阿拉伯语）',catalog:'参考资料（阿拉伯语）',save:'保存以供审核',saving:'保存中…',examples:['什么是伊赫桑？','伊斯兰教中的举意是什么？']},
  hi:{brand:'Madar Al Bayan',ask:'अपना प्रश्न पूछें',placeholder:'अपना प्रश्न यहाँ लिखें…',search:'खोजें',searching:'खोज जारी है…',close:'बंद करें',menu:'मेनू',source:'स्रोत',original:'स्रोत में प्रकाशित पाठ',hadith:'हदीस',explanation:'प्रकाशित व्याख्या',references:'मूल अरबी पाठ के संदर्भ',openSource:'स्रोत खोलें',copy:'कॉपी करें',copied:'कॉपी हो गया',error:'कुछ गड़बड़ हुई। फिर से प्रयास करें।',invalid:'1 से 1000 अक्षरों का प्रश्न लिखें।',busy:'वर्तमान खोज पूरी होने तक प्रतीक्षा करें।',insufficient:"संबंधित स्रोत पाठ नहीं मिला। छोटा प्रश्न या दूसरे शब्द आज़माएँ।",unavailable:'स्रोत का अनुवाद अभी उपलब्ध नहीं है। फिर से प्रयास करें।',draft:'एआई द्वारा तैयार मसौदा',draftNote:'मूल स्रोत से अलग है; समीक्षा आवश्यक है।',live:'सीधे स्रोत से',snapshot:'स्रोत का सहेजा गया पाठ',mixed:'ऑनलाइन और सहेजे गए स्रोत',retrieved:'प्राप्ति की तारीख',back:'खोज पर वापस जाएँ',cases:'समीक्षा फ़ाइलें (अरबी)',catalog:'संदर्भ सूची (अरबी)',save:'समीक्षा के लिए सहेजें',saving:'सहेजा जा रहा है…',examples:['इहसान क्या है?','इस्लाम में नीयत का क्या अर्थ है?']},
};
localizedCopy.fa={...localizedCopy.en,brand:'مدار البیان',ask:'پرسش خود را مطرح کنید',placeholder:'پرسش خود را بنویسید…',search:'جستجو',searching:'در حال جستجو…',close:'بستن',menu:'فهرست',source:'منبع',original:'متن منتشرشده در منبع',hadith:'حدیث',explanation:'شرح منتشرشده',references:'منابع متن اصلی عربی',openSource:'مشاهده منبع',copy:'کپی',copied:'کپی شد',error:'خطایی رخ داد. دوباره تلاش کنید.',insufficient:'متن مرتبطی به زبان شما در منابع متصل پیدا نشد.',unavailable:'دسترسی به منبع در حال حاضر ممکن نیست.',back:'بازگشت به جستجو',examples:['نیت چیست؟','رمضان']};
Object.assign(localizedCopy,extraLanguages.i18n);
// Interface fallback never substitutes the language of retrieved source texts.
export const copy:Record<string,Copy>=new Proxy(localizedCopy,{get:(target,key:string)=>target[key]??target.en});
