import extraLanguages from './added-language-copy.json';
type ReferralCopy={intro:string;email:string;consent:string;submit:string;saved:string;offline:string;failed:string};
const localized:Record<string,ReferralCopy>={
 en:{intro:'No matching answer was found in our connected sources in your language. You can submit your question for review.',email:'Your email',consent:'I agree to share my question and email with the review team to receive a reply.',submit:'Submit for review',saved:'Sent. Reference:',offline:'Email replies are not active yet. There is no confirmed reply date.',failed:'Could not save your question. Please try again later.'},
 ar:{intro:'لم نجد إجابة مناسبة بلغتك في المراجع المتصلة. يمكنك إرسال سؤالك للمراجعة الشرعية.',email:'بريدك الإلكتروني',consent:'أوافق على مشاركة سؤالي وبريدي مع فريق المراجعة لتلقي الرد.',submit:'إرسال للمراجعة',saved:'تم الإرسال برقم',offline:'الإرسال بالبريد لم يُفعّل بعد. لا يوجد موعد مؤكد للرد.',failed:'تعذر حفظ السؤال. حاول مرة أخرى لاحقًا.'},
 fr:{intro:'Aucune réponse pertinente dans votre langue n’a été trouvée dans nos sources connectées. Vous pouvez soumettre votre question pour examen.',email:'Votre adresse e-mail',consent:'J’accepte de partager ma question et mon adresse e-mail avec l’équipe de révision pour recevoir une réponse.',submit:'Soumettre pour examen',saved:'Envoyé sous le numéro',offline:'Les réponses par e-mail ne sont pas encore actives. Aucun délai de réponse n’est confirmé.',failed:'Impossible d’enregistrer votre question. Réessayez plus tard.'},
 es:{intro:'No se encontró una respuesta pertinente en tu idioma en nuestras fuentes conectadas. Puedes enviar tu pregunta para su revisión.',email:'Tu correo electrónico',consent:'Acepto compartir mi pregunta y mi correo con el equipo de revisión para recibir una respuesta.',submit:'Enviar para revisión',saved:'Enviado con el número',offline:'Las respuestas por correo aún no están activas. No hay una fecha de respuesta confirmada.',failed:'No se pudo guardar la pregunta. Inténtalo más tarde.'},
 zh:{intro:'在已连接的资料中未找到适合您问题的中文答案。您可以提交问题，等待审核。',email:'您的电子邮箱',consent:'我同意将问题和邮箱提供给审核团队，以便接收回复。',submit:'提交审核',saved:'已提交，编号：',offline:'邮件回复功能尚未启用，暂未确定回复日期。',failed:'无法保存问题，请稍后重试。'},
 hi:{intro:'जुड़े हुए स्रोतों में आपकी भाषा में उपयुक्त उत्तर नहीं मिला। आप अपना प्रश्न समीक्षा के लिए भेज सकते हैं।',email:'आपका ईमेल',consent:'उत्तर प्राप्त करने के लिए मैं अपना प्रश्न और ईमेल समीक्षा टीम के साथ साझा करने की सहमति देता/देती हूँ।',submit:'समीक्षा के लिए भेजें',saved:'भेज दिया गया। संदर्भ संख्या:',offline:'ईमेल से उत्तर भेजना अभी सक्रिय नहीं है। उत्तर की तारीख तय नहीं है।',failed:'प्रश्न सहेजा नहीं जा सका। बाद में फिर प्रयास करें।'},
 fa:{intro:'پاسخ مناسبی به زبان شما در منابع متصل یافت نشد. می‌توانید پرسش خود را برای بررسی شرعی ارسال کنید.',email:'ایمیل شما',consent:'موافقم پرسش و ایمیلم برای دریافت پاسخ با تیم بررسی به اشتراک گذاشته شود.',submit:'ارسال برای بررسی',saved:'ارسال شد، شمارهٔ پیگیری:',offline:'ارسال پاسخ با ایمیل هنوز فعال نیست. زمان مشخصی برای پاسخ تعیین نشده است.',failed:'ذخیره پرسش ممکن نشد. بعداً دوباره تلاش کنید.'},
};
Object.assign(localized,extraLanguages.referralCopy);
export function referralCopy(language:string){return localized[language]??localized.en;}
