import catalog from './resource-catalog.json';
import stats from './library-statistics.json';
export type Bilingual={ar:string;en:string};
export type ReferenceEntry={id:number;name:Bilingual;url:string;material:Bilingual;quantity:Bilingual;languages:Bilingual};
const pair=(ar:string,en:string):Bilingual=>({ar,en});
const seven=pair('العربية، الإنجليزية، الفرنسية، الإسبانية، الصينية، الهندية، الفارسية','Arabic, English, French, Spanish, Chinese, Hindi, Persian');
const nine=pair(seven.ar+'، الإندونيسية، الأردية',seven.en+', Indonesian, Urdu');
const arabic=pair('العربية','Arabic');
const variable=pair('لغات المحتوى قيد التوثيق','Content languages not yet verified');
const publisherCount=pair('العدد قيد التوثيق','Count not yet verified');
const row=(id:number,name:Bilingual,material:Bilingual,quantity:Bilingual,languages:Bilingual):ReferenceEntry=>({id,name,material,quantity,languages,url:catalog.rows.find(r=>r.id===id)!.url});
export const currentReferences:ReferenceEntry[]=[
 row(2,pair('موسوعة الأحاديث النبوية','HadeethEnc — Prophetic Hadith Encyclopedia'),pair('الأحاديث النبوية وشروحها وتخريجها وترجماتها المنشورة.','Prophetic hadith, explanations, source references and published translations.'),pair('٣٬٥٨٢ حديثًا؛ ٢٠٬٩٨٠ نص مع الترجمات في المكتبة','3,582 hadith; 20,980 texts including translations in the collection'),pair(nine.ar+'؛ و٦٣ لغة أخرى لدى الناشر',nine.en+'; 63 additional publisher languages')),
 row(1,pair('موسوعة القرآن الكريم','QuranEnc — Quran Encyclopedia'),pair('النص القرآني وترجمات معانيه مع الحواشي وبيانات الطبعة.','Quranic text and translations of its meanings, with notes and edition details.'),pair('٥٦٬١٢٤ نصًا مع الترجمات؛ ٦٬٢٣٦ آية · ١١٤ سورة','56,124 texts including translations; 6,236 verses · 114 surahs'),pair(nine.ar+'؛ وترجمات لدى الناشر بـ٤٨ لغة أخرى',nine.en+'; publisher translations in 48 additional languages')),
 row(6,pair('قاعدة المحتوى الإسلامي المركزية','ICADB — Central Islamic Content Database'),pair('نصوص الكتب والموسوعات والمصطلحات وترجماتها المعتمدة، ومنها مواد الموسوعة الإسلامية.','Book passages, encyclopedias, terminology and approved translations, including IslamEnc materials.'),pair('٦٠١ بطاقة عربية معتمدة: ٥٤٣ سؤالًا وجوابًا و٥٨ مصطلحًا؛ إضافة إلى البحث في مقاطع الكتب','601 approved Arabic cards: 543 questions and answers and 58 terms; plus book-passage search'),pair(nine.ar+'؛ البطاقات المحفوظة بالعربية، ولغات مقاطع الكتب بحسب المادة',nine.en+'; saved cards are Arabic, while book passages vary by item')),
 row(3,pair('الموسوعة القرآنية','Quranpedia'),pair('الآيات وتفاسيرها وترجمات معانيها، مع الإحالة إلى السورة والآية.','Quranic verses, commentary and translations referenced by surah and verse.'),pair('٦٬٢٣٦ آية · ١١٤ سورة؛ فهرس الناشر يضم ١٤٢ طبعة لترجمات المعاني','6,236 verses · 114 surahs; the publisher catalog lists 142 translation editions'),pair(nine.ar+'؛ و٥٢ لغة أخرى لترجمات المعاني لدى الناشر. التوافر بحسب الآية والطبعة',nine.en+'; publisher translations in 52 additional languages. Availability depends on verse and edition')),
 row(4,pair('سورة','Surah'),pair('تفسير السعدي، مع عرض موضع التفسير بحسب السورة والآية.','Al-Sa’di’s commentary, referenced by surah and verse.'),pair('تفسير واحد ضمن النطاق الحالي','1 commentary in the current collection'),arabic),
 row(8,pair('بيان الإسلام','Byenah — Introducing Islam'),pair('مواد تعريفية بالإسلام. تتضمن المكتبة الحالية مادة منشورة واحدة بإصداراتها اللغوية.','Introductory Islamic content. The current collection includes one published work in multiple language editions.'),pair('مادة واحدة · ٧ إصدارات لغوية محفوظة','1 work · 7 saved language editions'),seven),
 row(5,pair('المكتبة الصوتية للقرآن الكريم','MP3Quran — Quran Audio Library'),pair('تلاوات صوتية للسور، من تسجيلات الناشر الأصلية.','Surah recitations from the publisher’s original recordings.'),pair('المشغل: ١١٤ سورة. فهرس الناشر: ٢٤٢ قارئًا و٢٨٨ مجموعة تلاوة','Player: 114 surahs. Publisher catalog: 242 reciters and 288 recitation collections'),pair('التلاوة بالعربية. بيانات الناشر بالعربية والإنجليزية والفرنسية والإسبانية والصينية والفارسية والإندونيسية والأردية، و١٣ لغة أخرى. معلومات المشغل بالعربية والإنجليزية','Arabic recitation. Publisher metadata: Arabic, English, French, Spanish, Chinese, Persian, Indonesian, Urdu and 13 other languages. Player information: Arabic and English')),
 row(9,pair('دار الإسلام','IslamHouse'),pair('فهرس المقالات والمواد الدعوية ومرفقاتها الأصلية.','A catalog of articles, introductory materials and their original attachments.'),pair('٧٠٬٤٦٠ مادة في فهرس الناشر؛ منها ٤٬٦٧٧ مقالة باللغات التسع في فهرس المقالات المتاح','70,460 materials in the publisher catalog; including 4,677 article entries in the nine supported languages'),pair(nine.ar+'؛ و١٢٤ لغة أخرى لدى الناشر، بإجمالي ١٣٣ لغة',nine.en+'; 124 additional publisher languages, 133 in total')),
 row(27,pair('الموقع الرسمي للشيخ ابن باز','Sheikh Ibn Baz — Official Website'),pair('أجوبة مختارة في التعريف بالإسلام والعبادات والأخلاق، بنصها الأصلي ونسبتها إلى الشيخ.','Selected answers on Islam, worship and ethics, with original text and author attribution.'),pair('١٠١ إجابة منشورة محفوظة في المكتبة','101 published answers saved in the collection'),arabic),
];
export const upcomingReferences:ReferenceEntry[]=[
 row(7,pair('الدرر السنية — الموسوعة الحديثية','Dorar — Hadith Encyclopedia'),pair('الأحاديث وأحكام المحدّثين ومراجع الروايات.','Hadith, scholarly grading and narration references.'),publisherCount,arabic),
 row(10,pair('الموسوعة الإسلامية','IslamEnc — Islamic Encyclopedia'),pair('موسوعات وكتب ومحتوى إسلامي مترجم إضافي.','Additional encyclopedias, books and translated Islamic content.'),publisherCount,variable),
 row(11,pair('سوار — مجمع الملك سلمان','Siwar — King Salman Global Academy'),pair('المعاجم اللغوية والمصطلحات ومداخل الكلمات.','Language dictionaries, terminology and lexical entries.'),publisherCount,arabic),
 row(13,pair('مجمع الملك فهد — موارد القرآن','King Fahd Quran Printing Complex — Quran Resources'),pair('حزم النص القرآني والتفسير الميسر وبيانات المصحف.','Quranic text collections, concise commentary and mushaf data.'),publisherCount,arabic),
 row(14,pair('مجمع الملك فهد — ترجمات القرآن','King Fahd Quran Printing Complex — Quran Translations'),pair('الطبعات الرسمية لترجمات معاني القرآن الكريم.','Official editions of translations of the Quran’s meanings.'),publisherCount,variable),
 row(15,pair('مجمع الملك فهد — خطوط المصحف','King Fahd Quran Printing Complex — Quran Fonts'),pair('خطوط المصحف وأدوات عرض النص القرآني.','Mushaf fonts and Quranic text display resources.'),pair('موارد خطوط؛ لا تُعد منشورات معرفية','Font resources; not knowledge publications'),arabic),
 row(16,pair('المكتبة الشاملة','Al-Maktaba Al-Shamela'),pair('كتب التراث والعلوم الإسلامية مع الأجزاء والصفحات.','Classical and Islamic scholarship with volume and page references.'),publisherCount,arabic),
 row(17,pair('أوقاف الكويت — البحوث والموسوعة الفقهية','Kuwait Awqaf — Research and Fiqh Encyclopedia'),pair('بحوث شرعية ومواد الموسوعة الفقهية.','Islamic research and fiqh encyclopedia materials.'),publisherCount,arabic),
 row(18,pair('رسالة — رئاسة الشؤون الدينية','Risala — Presidency of Religious Affairs'),pair('مواد إرشادية وتعريفية للحجاج والمعتمرين.','Guidance and introductory materials for Hajj and Umrah visitors.'),publisherCount,variable),
 row(19,pair('المستودع الدعوي الرقمي','Digital Dawah Repository'),pair('كتب وبحوث وعروض وصوتيات ومرئيات تعريفية بالإسلام.','Books, research, presentations, audio and video introducing Islam.'),publisherCount,variable),
 row(20,pair('بينات: أسئلة وأجوبة عن الإسلام','Bayyinat — Questions and Answers about Islam'),pair('كتاب تعريفي بأسئلة وأجوبة عن الإسلام.','An introductory book of questions and answers about Islam.'),pair('كتاب واحد','1 book'),variable),
 row(21,pair('الجمهرة — المحتوى الإسلامي','Al-Jamhara — Islamic Content Encyclopedia'),pair('مفردات المحتوى الإسلامي وأعلامه وموضوعاته.','Islamic terminology, notable figures and subject entries.'),publisherCount,arabic),
 row(22,pair('الجمهرة — معجم المصطلحات الشرعية','Al-Jamhara — Dictionary of Islamic Terms'),pair('تعريفات المصطلحات الشرعية ومراجعها.','Definitions and references for Islamic terminology.'),publisherCount,arabic),
 row(23,pair('موسوعة التفسير الموضوعي','Thematic Quran Commentary Encyclopedia'),pair('دراسات موضوعات القرآن ومراجعها.','Studies of Quranic themes and their references.'),publisherCount,arabic),
 row(24,pair('مركز تفسير للدراسات القرآنية','Tafsir Center for Quranic Studies'),pair('بحوث ودراسات ومقالات في علوم القرآن.','Research, studies and articles on Quranic sciences.'),publisherCount,arabic),
 row(25,pair('وحي','Wahy'),pair('موارد وأدوات للدراسة القرآنية.','Resources and tools for Quranic study.'),publisherCount,variable),
 row(26,pair('الإسلام سؤال وجواب','Islam Question & Answer'),pair('أجوبة وفتاوى موثقة بالأدلة والمراجع.','Answers and fatwas supported by evidence and references.'),publisherCount,variable),
 row(28,pair('الموقع الرسمي للشيخ ابن عثيمين','Sheikh Ibn Uthaymeen — Official Website'),pair('فتاوى ودروس وكتب وصوتيات.','Fatwas, lessons, books and audio recordings.'),publisherCount,arabic),
 row(29,pair('الدرر السنية — التفسير','Dorar — Quran Commentary'),pair('تفسير وإعراب ومعاني وفوائد الآيات.','Commentary, grammar, meanings and lessons from Quranic verses.'),publisherCount,arabic),
 row(30,pair('الدرر السنية — العقيدة','Dorar — Islamic Creed'),pair('مباحث العقيدة وأدلتها ومراجعها.','Islamic creed, supporting evidence and references.'),publisherCount,arabic),
 row(31,pair('الدرر السنية — الفقه','Dorar — Islamic Jurisprudence'),pair('مسائل الفقه وأدلتها ومراجعها.','Jurisprudence, evidence and scholarly references.'),publisherCount,arabic),
 row(32,pair('الدرر السنية — التاريخ','Dorar — History'),pair('الأحداث التاريخية ومصادرها.','Historical events and their sources.'),publisherCount,arabic),
 row(33,pair('مجمع الملك سلمان العالمي للغة العربية','King Salman Global Academy for Arabic Language'),pair('المشروعات والمنشورات والمراجع اللغوية.','Language projects, publications and reference works.'),publisherCount,arabic),
 row(34,pair('معجم الرياض','Riyadh Dictionary'),pair('معاني الكلمات العربية المعاصرة وأمثلة الاستعمال.','Contemporary Arabic word meanings and usage examples.'),publisherCount,arabic),
 row(35,pair('فلك — مجمع الملك سلمان','Falak — King Salman Global Academy'),pair('المدونات النصية والسياقات والاستعمالات اللغوية.','Text corpora, linguistic contexts and usage.'),publisherCount,arabic),
];
const names:Record<string,Bilingual>={ar:pair('العربية','Arabic'),en:pair('الإنجليزية','English'),fr:pair('الفرنسية','French'),es:pair('الإسبانية','Spanish'),zh:pair('الصينية','Chinese'),hi:pair('الهندية','Hindi'),fa:pair('الفارسية','Persian'),id:pair('الإندونيسية','Indonesian'),ur:pair('الأردية','Urdu')};
export const libraryLanguageCounts=Object.entries(stats.languages).map(([code,n])=>({code,...names[code],texts:n.hadithTexts,explanations:n.explanations,quranVerses:n.quranVerses}));
