import extraLanguages from '@/lib/added-language-copy.json';
import type {Referral} from './referrals';
import {messageReference} from './message-labels';
import {siteInfo,committeeContactUrl} from './site-info';
type Labels={title:string;greeting:string;intro:string;question:string;answer:string;reference:string;sources:string;closing:string;team:string;contact:string;rights:string;publisherRights:string};
const labels:Record<string,Labels>={
 ar:{title:'الإجابة عن سؤالك',greeting:'أخي الكريم، أختي الكريمة،',intro:'شكرًا لتواصلك مع مدار البيان. يسعدنا أن نشاركك الرد على سؤالك.',question:'سؤالك',answer:'الإجابة عن سؤالك',reference:'رقم الرسالة',sources:'المراجع',closing:'نسعد بأسئلتك، ونرحّب بتواصلك في أي وقت.',team:'اللجنة المشرفة على مدار البيان',contact:'التواصل مع اللجنة المشرفة',rights:'جميع الحقوق محفوظة لمدار البيان.',publisherRights:'حقوق المواد المرجعية محفوظة لأصحابها.'},
 en:{title:'A reply to your question',greeting:'Dear friend,',intro:'Thank you for contacting Madar Al Bayan. We are glad to share our reply to your question.',question:'Your question',answer:'Our reply',reference:'Message number',sources:'References',closing:'Your questions are always welcome. Please feel free to contact us again.',team:'Madar Al Bayan Supervisory Committee',contact:'Contact the supervisory committee',rights:'All rights reserved. Madar Al Bayan.',publisherRights:'Reference materials belong to their respective publishers.'},
 fr:{title:'La réponse à votre question',greeting:'Bonjour,',intro:'Merci de votre confiance. Nous avons le plaisir de vous transmettre la réponse à votre question.',question:'Votre question',answer:'Notre réponse',reference:'Numéro du message',sources:'Références',closing:'Vos questions sont toujours les bienvenues. N’hésitez pas à nous recontacter.',team:'Comité de supervision de Madar Al Bayan',contact:'Contacter le comité de supervision',rights:'Tous droits réservés. Madar Al Bayan.',publisherRights:'Les documents de référence appartiennent à leurs éditeurs respectifs.'},
 es:{title:'La respuesta a tu pregunta',greeting:'Hola,',intro:'Gracias por contactar con Madar Al Bayan. Nos complace compartir la respuesta a tu pregunta.',question:'Tu pregunta',answer:'Nuestra respuesta',reference:'Número del mensaje',sources:'Referencias',closing:'Tus preguntas son siempre bienvenidas. Puedes volver a escribirnos cuando lo necesites.',team:'Comité supervisor de Madar Al Bayan',contact:'Contactar con el comité supervisor',rights:'Todos los derechos reservados. Madar Al Bayan.',publisherRights:'Los materiales de referencia pertenecen a sus respectivos editores.'},
 zh:{title:'关于您问题的回复',greeting:'您好！',intro:'感谢您联系 Madar Al Bayan。我们很高兴为您提供以下回复。',question:'您的问题',answer:'问题回复',reference:'留言编号',sources:'参考资料',closing:'欢迎您继续提问，随时与我们联系。',team:'Madar Al Bayan 监督委员会',contact:'联系监督委员会',rights:'版权所有。Madar Al Bayan。',publisherRights:'参考资料的版权归各出版方所有。'},
 hi:{title:'आपके प्रश्न का उत्तर',greeting:'प्रिय मित्र,',intro:'Madar Al Bayan से संपर्क करने के लिए धन्यवाद। हमें आपके प्रश्न का उत्तर साझा करते हुए प्रसन्नता हो रही है।',question:'आपका प्रश्न',answer:'हमारा उत्तर',reference:'संदेश संख्या',sources:'संदर्भ',closing:'आपके प्रश्नों का हमेशा स्वागत है। आप हमसे फिर संपर्क कर सकते हैं।',team:'Madar Al Bayan पर्यवेक्षण समिति',contact:'पर्यवेक्षण समिति से संपर्क करें',rights:'सर्वाधिकार सुरक्षित। Madar Al Bayan।',publisherRights:'संदर्भ सामग्री के अधिकार संबंधित प्रकाशकों के पास हैं।'},
 fa:{title:'پاسخ به پرسش شما',greeting:'دوست گرامی،',intro:'از اینکه با مدار البیان تماس گرفتید سپاسگزاریم. خوشحالیم که پاسخ پرسش شما را ارائه می‌کنیم.',question:'پرسش شما',answer:'پاسخ به پرسش شما',reference:'شماره پیام',sources:'منابع',closing:'پرسش‌های شما همیشه مایه خرسندی ماست. هر زمان خواستید با ما تماس بگیرید.',team:'کمیته نظارت مدار البیان',contact:'تماس با کمیته نظارت',rights:'تمامی حقوق برای مدار البیان محفوظ است.',publisherRights:'حقوق مطالب مرجع متعلق به ناشران آن‌هاست.'},
};
const escape=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
Object.assign(labels,extraLanguages.replyEmail);
export function replyEmail(row:Referral,number:number|null){
 const language=labels[row.language]?row.language:'en',t=labels[language],reference=messageReference(number,row.id),dir=['ar','fa','ur'].includes(language)?'rtl':'ltr',align=dir==='rtl'?'right':'left',year=new Date().getFullYear();
 const contact=siteInfo.contactEmail?'mailto:'+siteInfo.contactEmail:committeeContactUrl.replace('lang=en','lang='+language);
 let sources:string[]=[];try{const values:unknown=JSON.parse(row.sources);if(Array.isArray(values))sources=values.filter((v):v is string=>typeof v==='string'&&(()=>{try{return new URL(v).protocol==='https:';}catch{return false;}})());}catch{}
 const sourceText=sources.length?'\n\n'+t.sources+'\n'+sources.join('\n'):'';
 const sourceHtml=sources.length?`<h2 style="font-size:18px;margin:28px 0 12px">${escape(t.sources)}</h2>`+sources.map((url,index)=>`<p style="overflow-wrap:anywhere;margin:8px 0"><a style="color:#147567;text-decoration:underline" href="${escape(url)}">${escape(t.sources)} ${index+1} · <span dir="ltr">${escape(new URL(url).hostname)}</span></a></p>`).join(''):'';
 const html=`<!doctype html><html lang="${language}" dir="${dir}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>${escape(t.title)}</title><style>@media only screen and (max-width:600px){.mail-outer{padding:12px 6px!important}.mail-pad{padding:24px 20px!important}.mail-title{font-size:25px!important}.mail-box{padding:20px!important}}@media(prefers-color-scheme:dark){.mail-content{background:#ffffff!important;color:#172d3d!important}}</style></head>
<body style="margin:0;padding:0;background:#edf2f4;font-family:Tahoma,Arial,sans-serif;color:#172d3d;-webkit-text-size-adjust:100%">
<table role="presentation" lang="${language}" dir="${dir}" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td class="mail-outer" align="center" style="padding:32px 16px">
<!--[if mso]><table role="presentation" width="720" align="center" border="0" cellspacing="0" cellpadding="0"><tr><td><![endif]-->
<table class="mail-content" role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:720px;margin:0 auto;background:#ffffff;border:1px solid #dce6e9;border-radius:16px;overflow:hidden;text-align:${align}">
<tr><td class="mail-pad" bgcolor="#172f40" style="padding:30px 36px;border-bottom:4px solid #72c7b5"><p lang="ar" dir="rtl" style="font-size:26px;line-height:1.5;margin:0;color:#ffffff;text-align:${align}">مدار البيان</p><p dir="ltr" style="font-size:15px;letter-spacing:1px;line-height:1.5;margin:5px 0 0;color:#c6dedf;text-align:${align}">MADAR AL BAYAN</p></td></tr>
<tr><td class="mail-pad" style="padding:34px 36px;font-size:17px;line-height:1.9;text-align:${align}">
<p style="margin:0 0 12px;font-size:14px;color:#5f7884">${escape(t.reference)} <span dir="ltr" style="display:inline-block;white-space:nowrap;font-weight:bold;color:#30596a">${reference}</span></p>
<h1 class="mail-title" style="font-size:28px;line-height:1.5;font-weight:bold;margin:0 0 24px;color:#172f40">${escape(t.title)}</h1>
<p style="margin:0 0 8px;font-weight:bold">${escape(t.greeting)}</p><p style="margin:0 0 28px;color:#435f6d">${escape(t.intro)}</p>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin-bottom:28px"><tr><td class="mail-box" bgcolor="#f3f6f7" style="padding:24px;border:1px solid #e2e9ec;border-radius:12px;text-align:${align}"><h2 style="font-size:17px;margin:0 0 12px;color:#5d7682">${escape(t.question)}</h2><div dir="auto" style="white-space:pre-wrap;overflow-wrap:anywhere;word-break:break-word;font-size:17px;line-height:2">${escape(row.question)}</div></td></tr></table>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td class="mail-box" style="padding:28px;border:1px solid #b7d9cf;border-top:3px solid #147567;border-radius:12px;text-align:${align}"><h2 style="font-size:19px;margin:0 0 18px;color:#147567">${escape(t.answer)}</h2><div dir="auto" style="white-space:pre-wrap;overflow-wrap:anywhere;word-break:break-word;font-size:18px;line-height:2">${escape(row.answer)}</div>${sourceHtml}</td></tr></table>
<p style="margin:30px 0 8px;color:#526f7b;font-size:16px">${escape(t.closing)}</p><p style="margin:0;font-size:16px;font-weight:bold;color:#244958">${escape(t.team)}</p>
</td></tr>
<tr><td class="mail-pad" bgcolor="#f7fafb" style="padding:24px 36px;border-top:1px solid #e0e9ec;text-align:${align};font-size:14px;line-height:1.8"><a href="${escape(contact)}" style="color:#147567;text-decoration:underline;font-size:15px">${escape(t.contact)}</a>${siteInfo.contactEmail?`<p dir="ltr" style="margin:8px 0;text-align:${align}">${escape(siteInfo.contactEmail)}</p>`:''}<p style="margin:16px 0 4px;color:#536e7b">© ${year} ${escape(t.rights)}</p><p style="margin:0;color:#647e89">${escape(t.publisherRights)}</p><p style="margin:12px 0 0"><a href="${siteInfo.url}" style="color:#486a7a;text-decoration:none" dir="ltr">Madar Al Bayan</a></p></td></tr></table>
<!--[if mso]></td></tr></table><![endif]-->
</td></tr></table></body></html>`;
 return {subject:t.title+' | Madar Al Bayan | '+reference,text:'مدار البيان | Madar Al Bayan\n'+t.reference+': '+reference+'\n\n'+t.greeting+'\n'+t.intro+'\n\n'+t.question+'\n'+row.question+'\n\n'+t.answer+'\n'+row.answer+sourceText+'\n\n'+t.closing+'\n'+t.team+'\n\n'+t.contact+': '+(siteInfo.contactEmail||contact)+'\n© '+year+' '+t.rights+'\n'+t.publisherRights,html};
}
